### ISSUE TITLE
netcoreapp1.1 not working

### ISSUE THREAD

**Issue by valamelkor** [isukces/EfCore.Shaman#1]
Hi, 
First of all, I am want to thank you for very useful project to fix things missed from original EFCore. 
Missing column ordering is very annoying. 

However, I was not able to use you library properly in my ASP.NET Core project. 
I am trying to run apps on Windows AND Linux machines, so Windows-only is not an option at the moment. But I do not see any issues with this in your project.

I've added it to project json. Package restore told me that 

`Package EfCore.Shaman 1.0.16336.5 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package EfCore.Shaman 1.0.16336.5 supports: net451 (.NETFramework,Version=v4.5.1)`

Then I've added "net451" to imports for application in my project.json error above seems gone, but it seems that EFCore is not in references. I've tried to setup DbContext but VS told me that there is no namespace EfCore....

What could be an issue? 

My project json
```
{
  "userSecretsId": "some-string",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.1.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },
    "EfCore.Shaman": "1.0.16336.5"
  },

  "tools": {
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.1.0-preview4-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8",
        "net451"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle", "git rev-parse HEAD > wwwroot\\revision.txt" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by isukces** [comment]
EfCore.Shaman has not been tested on Core Framework. Try to use sources from GitHub instead of Nuget packages and make necessary changes. This is only workaround of course.

**Comment by borisdj** [comment]
Just to add some details on making .NetCore version of library for a workaround.
Create new .NetCore library and copy all code from EfCore.Shaman project.
On build there will be about 10 error, all the same type and fix is simple: add `.GetTypeInfo()`
Example
`type.IsGenericType
type.IsEnum`
...
becomes
`type.GetTypeInfo().IsGenericType
type.GetTypeInfo().IsEnum`

Isukces It would be nice if you could do this and add it also to the also nuget (EfCore.Shaman.NetFCore) so that is all in the same place.
It's 15 minutes work.
Btw thank for the library.

**Comment by borisdj** [comment]
One more thing
If I want tables to be singular without having to put [Table] attributes on all classes I used:
`foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())`
`  entityType.Relational().TableName = entityType.DisplayName();`
But when using that and this library, migration fails. Do you have any suggestions how to make both work?

**Comment by isukces** [comment]
Please register this as separate issue.

**Comment by borisdj** [comment]
With latest changes 2 additional fixes are needed for .NetCore 

First in _ShamanOptions.cs_ line
`dbContextType.GetMethod("GetShamanOptions", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[0], null);`
is replaced with
`dbContextType.GetTypeInfo().GetMethod("GetShamanOptions", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);`

Second problem(STILL NOT SOLVED) is in _ModelsCachedContainer.cs_
`public class ModelsCachedContainer : MarshalByRefObject`
there is no _MarshalByRefObject_ in .NetCore
I tried to remove it
`public class ModelsCachedContainer **//**: MarshalByRefObject`
after which I can build it but on creating migration get error:

_System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Method 'get_CurrentTransaction' in type 'Microsoft.EntityFrameworkCore.Storage.Internal.InMemoryTransactionManager' from assembly 'Microsoft.EntityFrameworkCore.InMemory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.InMemoryServiceCollectionExtensions.AddEntityFrameworkInMemoryDatabase(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_1.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at VideoRental.Db.VideoRentalContext..ctor(DbContextOptions`1 options) in D:\ProjectsMy\VideoRental\src\VideoRental\Db\VideoRentalContext.cs:line 28
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at EfCore.Shaman.ModelScanner.InstanceCreator.CreateInstanceInternal(Type contextType) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\InstanceCreator.cs:line 62
   at EfCore.Shaman.ModelScanner.InstanceCreator.CreateInstance(Type contextType, Object[] values) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\InstanceCreator.cs:line 26
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.TryCreateInstance(Type contextType) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\ModelsCachedContainer.cs:line 67
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.GetModel() in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\ModelsCachedContainer.cs:line 58
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.GetModel(Type dbContextType, Boolean raw) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\ModelsCachedContainer.cs:line 47
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.<>c.<GetRawModel>b__0_0(Type t) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\ModelsCachedContainer.cs:line 21
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.GetRawModel(Type dbContextType) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\ModelsCachedContainer.cs:line 19
   at EfCore.Shaman.ModelScanner.ModelInfo.Prepare() in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\ModelInfo.cs:line 118
   at EfCore.Shaman.ModelScanner.ModelInfo..ctor(Type dbContextType, IList`1 services) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelScanner\ModelInfo.cs:line 24
   at EfCore.Shaman.ModelFixer..ctor(Type dbContextType, ShamanOptions shamanOptions, ModelInfo modelInfo) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelFixer.cs:line 23
   at EfCore.Shaman.ModelFixer.<>c__DisplayClass2_0.<FixOnModelCreating>b__0() in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelFixer.cs:line 42
   at EfCore.Shaman.ModelFixer.FixingHolder.TryFix(Type contextType, Action action) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelFixer.cs:line 175
   at EfCore.Shaman.ModelFixer.FixOnModelCreating(ModelBuilder modelBuilder, Type contextType, ShamanOptions shamanOptions) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ModelFixer.cs:line 40
   at EfCore.Shaman.ShamanExtension.FixOnModelCreating(DbContext context, ModelBuilder modelBuilder, ShamanOptions shamanOptions) in D:\ProjectsMy\VideoRental\src\EfCore.Shaman\ShamanExtension.cs:line 31
   at VideoRental.Db.VideoRentalContext.OnModelCreating(ModelBuilder modelBuilder) in D:\ProjectsMy\VideoRental\src\VideoRental\Db\VideoRentalContext.cs:line 47
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation._

Any suggestions ?

**Comment by isukces** [comment]
MarshalByRefObject can be for sure removed everywhere. Please send me your .NET core version of Shaman for testing.

Seems that problem is outside Shaman. Try configure your VideoRentalContext with Microsoft.EntityFrameworkCore.InMemory storage and then make some sb operation using transactions.

**Comment by borisdj** [comment]
Here it is [link](https://dl.dropboxusercontent.com/u/70690624/EfCore.Shaman.NetCore.zip)

**Comment by isukces** [comment]
Some csfiles has been updated and .NetCore version compiles succesfully. Xunit tests gives some errors so extra work still behind me.

Due to [MsBuild issue](https://github.com/Microsoft/msbuild/issues/394) csproj and packages.config can't coexist with xproj and project.json.  My own priority (sorry) is to maintain .Net framework version so files necessary for .NET Core compilation are provided in separate directory.

**Comment by borisdj** [comment]
I can confirm that it compiles now but still gives the same error on creating migration.
Do you plan to try make it work for Core version, even if it is in separate folder.

**Comment by isukces** [comment]
.NET Core version is not my priority now. First I want to fix as many annoying EF problems as possible. 

Moreover it seems that this technology is not mature enough. Many developers advise to wait for version 2.0. I don't want to waste time to workaround problems that brings Visual Studio or not implemented parts of .NET.

For sure .NET Core is a future of this project.

**Comment by borisdj** [comment]
Ok, in that case if anyone would need now .Core version, last I could made it work was:
[https://github.com/isukces/EfCore.Shaman/tree/3479803b818d841fb22d8468f020045b45f4538e](https://github.com/isukces/EfCore.Shaman/tree/3479803b818d841fb22d8468f020045b45f4538e)
And required workaround fixes are .GetTypeInfo() and GetMethod( that were mention in previous comments.
For making singular table names more details are on [issue 3](https://github.com/isukces/EfCore.Shaman/issues/3) since this commit did not have it yet then.

**Comment by isukces** [comment]
I've just fixed problem with InMemory provider. Stuppid mistake was a source of it. Please test Shaman now and send response. From my side all unit test pass bot in full and core framework.

**Comment by borisdj** [comment]
Now it works fine.

**Comment by borisdj** [comment]
However there are still few lines where adding `.GetTypeInfo()` is required, in
_ShamanOptions.cs, InstanceCreator.cs_ and _ModelInfo.cs_
