### ISSUE TITLE
Added command timeout in DbContext constructor encounterred error when do database update

### ISSUE THREAD

**Issue by viewtance** [isukces/EfCore.Shaman#12]
I add command timeout in the constructor of DbConext, when doing database update it throw below exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Storage.IRelationalConnection'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.SetCommandTimeout(DatabaseFacade databaseFacade, Nullable`1 timeout)

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at EfCore.Shaman.ModelScanner.InstanceCreator.CreateInstanceInternal(Type contextType)
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.TryCreateInstance(Type contextType)
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.GetModelInternal()
   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.GetModel(Type dbContextType, Boolean raw, IShamanLogger logger)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at EfCore.Shaman.ModelScanner.ModelInfo.Prepare()
   at EfCore.Shaman.ModelFixer.FixMigrationUp[T](MigrationBuilder migrationBuilder, ShamanOptions shamanOptions)
   at MyProject.Migrations.Add_Equipment_Related_Entities.Up(MigrationBuilder migrationBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by isukces** [comment]
Two solutions possible 
1. Don't delete previous construction (keep old and new one). 
2. Better way is to provide static method `GetDbContext` in DbContext class. i.e.
```
public static YourDbContext GetDbContext()
{
    return new YourDbContext(/* all necessary parameters*/);
 }
```
Shaman will use `GetDbContext` method for creating unpached version of dbContext necessary for its internal operations.
