### ISSUE TITLE
In EFCore2.0 Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.IEntityType.get_ClrType()'.

### ISSUE THREAD

**Issue by borisdj** [isukces/EfCore.Shaman#18]
.NET Core 2.0 with **EFCore 2.0** was just released 2 days ago.
Am I testing to see if switch to it will be easy.
I have created .NetCore2.0 app WebAPI that is targeting full .NetFramework.
Then done few add-migration and they worked.
But when I included **EfCore.Shaman** and added call `this.FixOnModelCreating(modelBuilder)`
got the following error:

> PM> add-migration Initial
> System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.IEntityType.get_ClrType()'.
>    at EfCore.Shaman.ModelScanner.EfModelWrapper.EfModelEntityWrapper.FromIEntityType(IEntityType entityType)
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at EfCore.Shaman.ModelScanner.EfModelWrapper.FromModel(IModel model)
>    at EfCore.Shaman.ModelScanner.ModelsCachedContainer.SetRawModel(Type type, IMutableModel model, IShamanLogger logger)
>    at EfCore.Shaman.ModelFixer.FixOnModelCreating(ModelBuilder modelBuilder, Type contextType, ShamanOptions shamanOptions)
>    at EfCore.Shaman.ShamanExtension.FixOnModelCreating(DbContext context, ModelBuilder modelBuilder, ShamanOptions shamanOptions)
>    at MvcMovie.Data.TyrollContext.OnModelCreating(ModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
>    at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.IEntityType.get_ClrType()'.

**Comment by borisdj** [comment]
Could you publish this fix because currently it is blocking the usage of library on Core 2.0
If you want I can send you a pull request, but it's only one line of code.

**Comment by mkoflerAT** [comment]
I'm affected as well - A fix would be greatly appreciated! Status on this issue?

**Comment by isukces** [comment]
I afraid that it is not a solution. Actually `entityType.GetType()` returns type of class implementing `IEntityType` (i.e. `Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType`) not type of entity class related to DbContext. Insert following snipped into `protected override void OnModelCreating(ModelBuilder modelBuilder)`
```
IEntityType et = modelBuilder.Model.GetEntityTypes().First();
Debug.WriteLine($"ClrType={et.ClrType} from {et.ClrType.Assembly.FullName}");
Debug.WriteLine($"GetType()={et.GetType()} from {et.GetType().Assembly.FullName}");
```
and verify output. On my test code it returns 
```
ClrType=EfCore.Shaman.Tests.Model.MySettingsEntity from EfCore.Shaman.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
GetType()=Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType from Microsoft.EntityFrameworkCore, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```
A proper way to solve problem is to recompile Shaman with Ef20 + Framework461.

**Comment by borisdj** [comment]
Yes, I get the same result only the EF Version is 2.0:
`...from Microsoft.EntityFrameworkCore, Version=2.0.0.0, ...`

So can you recompile it or if you have suggestions on some temporary fix?

Also now that besides EFCore 2.0, also NetCore 2.0 along with NetStandard 2.0 is released you could consider targeting NetStandard 2.0.
Maybe not immediately but in some near future.

**Comment by isukces** [comment]
At this moment I'm almost finished targetting  Ef20 + Framework461. I have problem with `nuget restore` when `TargetTrameworks` in `csproj` contains `netstandard2.0` - msbuild just crash on `WriteRestoreGraphTask`.

**Comment by isukces** [comment]
Just finished
- github repository updated
- https://www.nuget.org/packages/EfCore.Shaman/1.0.17240.66
- https://www.nuget.org/packages/EfCore.Shaman.SqlServer/1.0.17240.59

I hope that I'll find a way to manage nuget restore problem soon.

**Comment by borisdj** [comment]
Latest versions work with EFCore2.0.
Great work.

**Comment by Systemdir** [comment]
I still get the same error message when calling FixOnModelCreating:
> Exception thrown: 'System.MissingMethodException' in EfCore.Shaman.dll
> An exception of type 'System.MissingMethodException' occurred in EfCore.Shaman.dll but was not handled in user code: 'Method not found: 'System.Type 
> Microsoft.EntityFrameworkCore.Metadata.IEntityType.get_ClrType()'.'
> Stack trace:
 >   at EfCore.Shaman.ModelScanner.EfModelWrapper.EfModelEntityWrapper.FromIEntityType(IEntityType entityType)
 >   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
 >   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 >   at EfCore.Shaman.ModelScanner.EfModelWrapper.FromModel(IModel model)
 >   at EfCore.Shaman.ModelScanner.ModelsCachedContainer.SetRawModel(Type type, IMutableModel model, IShamanLogger logger)
 >   at EfCore.Shaman.ModelFixer.FixOnModelCreating(ModelBuilder modelBuilder, Type contextType, ShamanOptions shamanOptions)

.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EfCore.Shaman" Version="1.0.17240.66" />
    <PackageReference Include="JetBrains.Annotations" Version="11.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0" />
  </ItemGroup>
  
  (...)
</Project>
```

**Comment by isukces** [comment]
As I wrote before I have problem with targetting to `netstandard2.0`. You can try to compile libraries from sources.

Moreover I found big changes in EfCore2.0 and its dependences during tests on net461. In fact I was unable to migrate my private project based on Serenity into 2.0 platform. So I decided to release separate set of packages (soon on nuget).

One of the problem was with one-to-one relation defined in model that produces proper migration in 1.1.2 but crashes in 2.0. I gave up with this.

- `EfCore.Shaman` + `EfCore.Shaman.SqlServer` (`net461`) designed for EfCore 2.0
- `EfCore.Shaman112` + `EfCore.Shaman112.SqlServer` (`net451`+`netstandard1.6`) designed for EfCore 1.1.2 for compatibility reason

You can review [changes](https://github.com/isukces/EfCore.Shaman/commit/659a6fbf4365eb0e339bae695f05a6989241acca). I switched to `EfCore.Shaman112` in my Serenity based project.

**Comment by Systemdir** [comment]
Thank you for the clarification 👍 
I look forward to the nuget release.

**Comment by Jose7777** [comment]
I look forward to the nuget release too.
What is the estimated release date?

Thank you for your hard work.

**Comment by Systemdir** [comment]
Still no information on the ETA of the nuget release?

**Comment by isukces** [comment]
Please update information: 
a) what exactly nuget packages version do you use 
b) what is current call stack of exception. 
c) what is target platform/framework of your project

**Comment by Systemdir** [comment]
I'm sorry, I just found out that I still reference the old nuget release.
The problems disappeared with the 1.0.17277.68 release.

**Comment by Systemdir** [comment]
<TargetFramework>netstandard2.0</TargetFramework>

Warning:

      Package ' EfCore.Shaman 1.0.17277.68' was restored using '.NETFramework,Version=v.4.6.1'  
      instead of  the project target framework '.NETStandard,Version=v2.0'. 
      This package may not be fully compatible with your project.

Appart from that the library seems to work as intended.

**Comment by borisdj** [comment]
I have also just tested it (1.0.17277.68) by creating new project that is targeting .NET Core 2.0
It works but has this warning that can be annoying.
Could that be resolved.

**Comment by borisdj** [comment]
Temporary fix to hide the warning:
In Solution Explorer select this library, then on it's Properties panel add following into NoWarn field:
NU1701
